{
  "openapi": "3.0.3",
  "info": {
    "title": "UCRI Control Room Module (UCRM) API",
    "description": "UCRI Control Room Module API ist die Kommunikationsschnittstelle für verbundene UCRI Kommunikationsteilnehmer\nwie zum Beispiel Leitstellensysteme, andere technische Knoten, sowie weitere externe Systeme.\n",
    "version": "0.1"
  },
  "servers": [
    {
      "url": "{apiRoot}/{basePath}",
      "variables": {
        "apiRoot": {
          "default": "https://ucri.mycompany.com",
          "description": "API root",
          "enum": [
            "https://ucri.mycompany.com"
          ]
        },
        "basePath": {
          "default": "ucrm/v0",
          "description": "API base path"
        }
      }
    }
  ],
  "tags": [
    {
      "name": "Messaging",
      "description": "Der Messaging Service beinhaltet Funktionen zum Versenden und Empfangen von Nachrichten, die im Rahmen der UCRI Spezifikation spezifiziert sind."
    },
    {
      "name": "Registry"
    },
    {
      "name": "Info"
    }
  ],
  "paths": {
    "/messaging/send": {
      "post": {
        "tags": [
          "Messaging"
        ],
        "summary": "Meldung senden",
        "description": "Meldung senden",
        "operationId": "sendMessage",
        "requestBody": {
          "description": "Zu versendende Meldung",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/senderRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK, versendete Meldung",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/senderResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/messaging/receive": {
      "post": {
        "tags": [
          "Messaging"
        ],
        "summary": "Meldungen empfangen",
        "description": "Meldungen im Empfangspuffer abfragen. Empfangspuffer ist als eine FIFO-Queue pro Adressat-OID aufgebaut. Es werden die ältesten X Meldungen aus der Adressaten-Queue geliefert.",
        "operationId": "receiveMessages",
        "requestBody": {
          "description": "Meldungsabfrage",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/receiverRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK \\\nMindestens eine und bis zu 'maxMessages' ältesten Meldungen werden geliefert.\n",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/receiverResponse"
                }
              }
            }
          },
          "204": {
            "description": "No Content \\\nEs liegen aktuell keine Nachrichten in der Adressaten-Queue vor.\n"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/messaging/commit": {
      "post": {
        "tags": [
          "Messaging"
        ],
        "summary": "Meldungsempfang bestätigen",
        "description": "Empfang von Meldungen bis einschliesslich angegebene Meldung (Sequence-ID) bestätigen. Nach dem Commiten einer Sequence-ID werden alle Meldungen mit kleinerer oder gleicher Sequence-ID aus der Queue entfernt.",
        "operationId": "commitMessage",
        "requestBody": {
          "description": "Meldungsreferenz",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/messageRef"
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/registry": {
      "get": {
        "tags": [
          "Registry"
        ],
        "summary": "KT-Register abfragen",
        "description": "Liefert eine Liste aller Kommunikationsteilnehmer.",
        "operationId": "listCommParticipant",
        "responses": {
          "200": {
            "description": "OK, Liste aller Kommunikationsteilnehmer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "commParticipants": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/commParticipant"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/registry/{id}": {
      "get": {
        "tags": [
          "Registry"
        ],
        "summary": "Informationen zu einem KT abfragen",
        "description": "Informationen zu einem KT abfragen",
        "operationId": "readCommParticipant",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "KT-OID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK, Informationen zu einem KT",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/commParticipant"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/info": {
      "get": {
        "tags": [
          "Info"
        ],
        "summary": "UCRM Information",
        "description": "Liefert UCRM Information",
        "operationId": "info",
        "responses": {
          "200": {
            "description": "OK, UCRM Information",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/info"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Envelope": {
        "$ref": "#/components/schemas/envelope"
      },
      "SenderRequest": {
        "$ref": "#/components/schemas/senderRequest"
      },
      "SenderResponse": {
        "$ref": "#/components/schemas/senderResponse"
      },
      "ReceiverRequest": {
        "$ref": "#/components/schemas/receiverRequest"
      },
      "ReceiverResponse": {
        "$ref": "#/components/schemas/receiverResponse"
      },
      "MessageRef": {
        "$ref": "#/components/schemas/messageRef"
      },
      "CommParticipant": {
        "$ref": "#/components/schemas/commParticipant"
      },
      "Info": {
        "$ref": "#/components/schemas/info"
      },
      "Error": {
        "required": [
          "code",
          "reason"
        ],
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "description": "Anwendungsspezifische Fehler-Code"
          },
          "reason": {
            "type": "string",
            "description": "Fehlerursache in für Menschen verständlicher Sprache"
          },
          "message": {
            "type": "string",
            "description": "Detailliertere Fehlerbeschreibung eventuell mit Angabe der Korrektivmaßnahmen in für Menschen verständlicher Sprache"
          }
        },
        "description": "Fehlerbeschreibung, gewöhnlich für eine HTTP Error Response-Code (3xx, 4xx, 5xx)"
      },
      "payload": {
        "required": [
          "appId",
          "appVersion",
          "schemaId",
          "contentType",
          "data"
        ],
        "type": "object",
        "properties": {
          "appId": {
            "type": "string",
            "description": "Name der UCRI2-Applikation"
          },
          "appVersion": {
            "type": "string",
            "description": "Version der UCRI2-Applikation"
          },
          "schemaId": {
            "type": "string",
            "description": "Name des Schemas für diese Nachricht"
          },
          "contentType": {
            "type": "string",
            "enum": [
              "application/json",
              "application/jose"
            ],
            "description": "Inhalt der übergebenen Nachricht, application/json - unverschlüsselte Nachricht, application/jose - verschlüsselte Nachricht"
          },
          "data": {
            "type": "string",
            "format": "binary",
            "description": "Applikationsspezifische Nachricht, Inhalt entsprechend dem 'contentType'"
          }
        },
        "description": "Applikationsspezifische Nachricht mit Meta-Informationen",
        "example": {
          "appId": "incident_transfer",
          "appVersion": "0.1",
          "schemaId": "transfer",
          "contentType": "application/json",
          "data": "{\"issue\":\"Brandeinsatz\",\"location\":{\"country\":\"NRW\",\"city\":\"Düsseldorf\",\"postalCode\":\"40210\",\"street\":\"Musterstrasse\",\"houseNumber\":\"42\"},\"id\":\"550e8400-e29b-41d4-a716-446655440000\",\"type\":\"Brandeinsatz\",\"keyword\":\"F 2\"}"
        }
      },
      "envelope": {
        "required": [
          "source",
          "payload"
        ],
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "Freitext-Beschreibung einer Meldung"
          },
          "messageId": {
            "type": "string",
            "format": "uuid",
            "description": "Meldungs-ID - dient der formalen Verarbeitung und Zuordnung der Meldung. Falls nicht übergeben, wird die Meldungs-ID automatisch generiert. Bei der Weiterleitung einer Meldung zwischen CRM (Routing) muss die ursprüngliche Meldungs-ID weitergegeben werden."
          },
          "sentDate": {
            "type": "string",
            "format": "date-time",
            "description": "Sendedatum Falls nicht übergeben, wird das Sendedatum automatisch gesetzt. Bei der Weiterleitung einer Meldung zwischen CRM (Routing) soll das ursprüngliche Sendedatum weitergegeben werden."
          },
          "timeout": {
            "type": "integer",
            "description": "Anzahl der Sekunden, welche die Meldung auf der Vermittlungsebene verweilen darf, bevor die Zustellversuche abgebrochen und die Meldung - mit Fehlermeldung an den Sender - verworfen wird. Defaultwert falls nicht definiert. Bei der Weiterleitung einer Meldung zwischen CRM (Routing) soll das ursprüngliche Timeout weitergegeben werden.",
            "default": 3600,
            "minimum": 10,
            "maximum": 86400
          },
          "ack": {
            "type": "string",
            "description": "Erwartete technische Bestätigung, NONE - keine Bestätigungen, NACK - nur negative Bestätigungen, ALL - alle Bestätigungen",
            "enum": [
              "NONE",
              "NACK",
              "ALL"
            ],
            "default": "NONE"
          },
          "source": {
            "type": "string",
            "pattern": "^([0-9]+\\.?)+$",
            "description": "Sender-Adresse, OID"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Liste an Zeichenketten, die eine inhaltliche Zusammenführung von Nachrichten zu einem Thema erlauben."
          },
          "payload": {
            "$ref": "#/components/schemas/payload"
          },
          "signature": {
            "type": "string",
            "description": "eine Signatur der Nachricht zur Überprüfung ihrer Authentizität und Unverfälschtheit, formatiert als JWS Compact Serialization, siehe https://datatracker.ietf.org/doc/html/rfc7517"
          }
        },
        "description": "Nachrichtenumschlag, enthält Metainformationen zu einer Meldung und die eigentliche Meldung als Payload"
      },
      "senderRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/envelope"
          },
          {
            "type": "object",
            "required": [
              "destinations"
            ],
            "properties": {
              "destinations": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^([0-9]+\\.?)+$"
                },
                "minItems": 1,
                "maxItems": 1,
                "description": "Empfänger-Adressen, OID-Liste. In der UCRI 2.0 kann eine Nachricht nur an einen Empfänger gesendet werden. Diese Einschränkung kann in späteren UCRI-Versionen rückwärtskompatibel aufgehoben werden."
              }
            },
            "example": {
              "description": "Einsatzübergabe am 13.11.2023 um 20:20",
              "timeout": 300,
              "ack": "NACK",
              "source": "1.2.3.4.5.6",
              "destinations": [
                "1.2.3.4.5.7"
              ],
              "payload": {
                "appId": "incident_transfer",
                "appVersion": "0.1",
                "schemaId": "incident",
                "contentType": "application/json",
                "data": "{\"sharedIncidentId\":\"550e8400-e29b-41d4-a716-446655440000\",\"internalId\":\"f123456\",\"classifications\":[\"A1\",\"F2\"],\"issue\":\"Notfall\",\"flashingLights\":true,\"additionalInfo\":\"Zusatzinformationen\",\"sentByDispatcherAt\":\"2024-01-01T10:05:08Z\",\"startTimestamp\":\"2024-01-01T09:55:15Z\",\"missionLocation\":{\"coordinate\":{\"lat\":65.453323,\"lon\":14.542343},\"address\":{\"street\":\"Musterstrasse\",\"houseNumber\":\"15b\",\"postalCode\":\"12345\",\"city\":\"Musterhausen\",\"cityDistrict\":\"Musterberg\",\"state\":\"Brandenburg\",\"country\":\"DE\"},\"object\":{\"name\":\"Abteilung IV, Haus 3\",\"additionalInfo\":\"Campus West\"},\"superiorObject\":{\"name\":\"Krankenhaus Musterstift\",\"additionalInfo\":\"Weitere Informationen\"},\"floor\":\"3. OG\",\"room\":\"412\",\"additionalInfo\":\"Weitere Informationen\"},\"informers\":[{\"name\":\"Musterfrau\",\"surname\":\"Heike\",\"phone\":\"+49 30 234567\",\"email\":\"heike.musterfrau@example.com\"}]}"
              }
            }
          }
        ]
      },
      "senderResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/envelope"
          },
          {
            "type": "object",
            "required": [
              "messageId",
              "sentDate",
              "timeout",
              "ack",
              "destinations"
            ],
            "properties": {
              "destinations": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^([0-9]+\\.?)+$"
                },
                "minItems": 1,
                "maxItems": 1,
                "description": "Empfänger-Adressen, OID-Liste. In der UCRI 2.0 kann eine Nachricht nur an einen Empfänger gesendet werden. Diese Einschränkung kann in späteren UCRI-Versionen rückwärtskompatibel aufgehoben werden."
              }
            },
            "example": {
              "messageId": "f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454",
              "description": "Einsatzübergabe am 13.11.2023 um 20:20",
              "sentDate": "2023-11-13T20:20:39+00:00",
              "timeout": 300,
              "ack": "NACK",
              "source": "1.2.3.4.5.6",
              "destinations": [
                "1.2.3.4.5.7"
              ],
              "payload": {
                "appId": "incident_transfer",
                "appVersion": "0.1",
                "schemaId": "incident",
                "contentType": "application/json",
                "data": "{\"issue\":\"Brandeinsatz\",\"location\":{\"country\":\"NRW\",\"city\":\"Düsseldorf\",\"postalCode\":\"40210\",\"street\":\"Musterstrasse\",\"houseNumber\":\"42\"},\"id\":\"550e8400-e29b-41d4-a716-446655440000\",\"type\":\"Brandeinsatz\",\"keyword\":\"F 2\"}"
              },
              "signatur": "eyJhbGciOiJSUzI1NiJ9 . eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGFt cGxlLmNvbS9pc19yb290Ijp0cnVlfQ . cC4hiUPoj9Eetdgtv3hF80EGrhuB__dzERat0XF9g2VtQgr9PJbu3XOiZj5RZmh7 AAuHIm4Bh-0Qc_lF5YKt_O8W2Fp5jujGbds9uJdbF9CUAr7t1dnZcAcQjbKBYNX4 BAynRFdiuB--f_nZLgrnbyTyWzO75vRK5h6xBArLIARNPvkSjtQBMHlb1L07Qe7K 0GarZRmB_eSN9383LcOLn6_dO--xi12jzDwusC-eOkHWEsqtFZESc6BfI7noOPqv hJ1phCnvWh6IeYI2w9QOYEUipUTI8np6LbgGY9Fs98rqVt5AXLIhWkWywlVmtVrB p0igcN_IoypGlUPQGe77Rw"
            }
          }
        ]
      },
      "receiverRequest": {
        "required": [
          "destinations"
        ],
        "type": "object",
        "properties": {
          "destinations": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^([0-9]+\\.?)+$"
            },
            "minItems": 1,
            "description": "Adressatenliste, Meldungen an alle Adressen aus dieser Liste werden abgefragt. Gleichzeitig werden Meldungen an alle Adressen aus dem OID-Unterbaum des Adressaten abgefragt. Siehe UCRI2 Adressierungskonzept, Systemkomponente Gateway."
          },
          "maxMessages": {
            "type": "integer",
            "minimum": 1,
            "description": "maximale Anzahl von Meldungen im Ergebnis, Defaultwert wenn nicht definiert"
          }
        },
        "description": "Meldungsabfrage",
        "example": {
          "destinations": [
            "1.2.3.4.5.7"
          ],
          "maxMessages": 5
        }
      },
      "receiverResponseItem": {
        "allOf": [
          {
            "$ref": "#/components/schemas/envelope"
          },
          {
            "type": "object",
            "required": [
              "messageId",
              "destination",
              "sequenceId",
              "sentDate",
              "timeout"
            ],
            "properties": {
              "destination": {
                "type": "string",
                "pattern": "^([0-9]+\\.?)+$"
              },
              "sequenceId": {
                "type": "integer",
                "format": "int64",
                "description": "Meldungs-Sequence-ID Empfangspuffer ist als eine FIFO-Queue pro Adressat-OID aufgebaut. Sequence-ID wird verwendet um die erfolgreiche Verarbeitung einer Meldung durch Commit-Operation zu signalisieren. Nach dem Commiten einer Sequence-ID werden alle Meldungen mit kleinerer oder gleicher Sequence-ID aus der Queue entfernt."
              }
            }
          }
        ]
      },
      "receiverResponse": {
        "required": [
          "messages",
          "maxMessages"
        ],
        "type": "object",
        "properties": {
          "messages": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/receiverResponseItem"
            },
            "minItems": 1
          },
          "maxMessages": {
            "type": "integer",
            "minimum": 1,
            "description": "maximale Anzahl von Meldungen im Ergebnis"
          }
        },
        "description": "Die bis zu 'maxMessages' ältesten X Meldungen entsprechend der Meldungsabfrage",
        "example": {
          "messages": [
            {
              "messageId": "f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454",
              "description": "Einsatzübergabe am 13.11.2023 um 20:20",
              "sentDate": "2023-11-13T20:20:39+00:00",
              "timeout": 300,
              "ack": "NACK",
              "source": "1.2.3.4.5.6",
              "destination": "1.2.3.4.5.7",
              "sequenceId": 123456,
              "payload": {
                "appId": "incident_transfer",
                "appVersion": "0.1",
                "schemaId": "incident",
                "contentType": "application/json",
                "data": "{\"issue\":\"Brandeinsatz\",\"location\":{\"country\":\"NRW\",\"city\":\"Düsseldorf\",\"postalCode\":\"40210\",\"street\":\"Musterstrasse\",\"houseNumber\":\"42\"},\"id\":\"550e8400-e29b-41d4-a716-446655440000\",\"type\":\"Brandeinsatz\",\"keyword\":\"F 2\"}"
              },
              "signatur": "eyJhbGciOiJSUzI1NiJ9 . eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGFt cGxlLmNvbS9pc19yb290Ijp0cnVlfQ . cC4hiUPoj9Eetdgtv3hF80EGrhuB__dzERat0XF9g2VtQgr9PJbu3XOiZj5RZmh7 AAuHIm4Bh-0Qc_lF5YKt_O8W2Fp5jujGbds9uJdbF9CUAr7t1dnZcAcQjbKBYNX4 BAynRFdiuB--f_nZLgrnbyTyWzO75vRK5h6xBArLIARNPvkSjtQBMHlb1L07Qe7K 0GarZRmB_eSN9383LcOLn6_dO--xi12jzDwusC-eOkHWEsqtFZESc6BfI7noOPqv hJ1phCnvWh6IeYI2w9QOYEUipUTI8np6LbgGY9Fs98rqVt5AXLIhWkWywlVmtVrB p0igcN_IoypGlUPQGe77Rw"
            }
          ],
          "maxMessages": 5
        }
      },
      "messageRef": {
        "required": [
          "destination",
          "sequenceId"
        ],
        "type": "object",
        "properties": {
          "destination": {
            "type": "string",
            "pattern": "^([0-9]+\\.?)+$",
            "description": "Adressat, diese Referenz zeigt auf eine Meldung, die genau an diese OID adressiert wurde, nicht an eine OID aus einem Unterbaum"
          },
          "sequenceId": {
            "type": "integer",
            "format": "int64",
            "description": "eine aufsteigende Meldung-Sequence-ID"
          }
        },
        "description": "Meldungsreferenz",
        "example": {
          "destination": "1.2.3.4.5.6",
          "sequenceId": 123456
        }
      },
      "appRef": {
        "required": [
          "appId",
          "appVersion"
        ],
        "type": "object",
        "properties": {
          "appId": {
            "type": "string",
            "description": "Name der UCRI2-Applikation"
          },
          "appVersion": {
            "type": "string",
            "description": "Version der UCRI2-Applikation"
          }
        },
        "description": "Referenz auf eine UCRI2-Applikation",
        "example": {
          "appId": "incident",
          "appVersion": "0.1"
        }
      },
      "techSupport": {
        "required": [
          "phone",
          "e-mail"
        ],
        "type": "object",
        "properties": {
          "phone": {
            "type": "string",
            "description": "Telefonnummer des technischen Supports"
          },
          "e-mail": {
            "type": "string",
            "description": "E-Mail des technischen Supports"
          },
          "address": {
            "type": "string",
            "description": "Postadresse des technischen Supports"
          }
        },
        "description": "Kontakt zum technischen Support",
        "example": {
          "phone": "+49 69 123456",
          "e-mail": "support@lst-essen.de",
          "address": "Musterstraße 1, 45133 Essen"
        }
      },
      "jwkRsaPub": {
        "required": [
          "kty",
          "n",
          "e"
        ],
        "type": "object",
        "properties": {
          "kty": {
            "type": "string",
            "enum": [
              "RSA"
            ],
            "description": "Key Type Parameter"
          },
          "n": {
            "type": "string",
            "format": "base64url",
            "description": "The \"n\" (modulus) parameter contains the modulus value for the RSA public key. It is represented as a Base64urlUInt-encoded value."
          },
          "e": {
            "type": "string",
            "format": "base64url",
            "description": "The \"e\" (exponent) parameter contains the exponent value for the RSA public key. It is represented as a Base64urlUInt-encoded value."
          }
        },
        "description": "RSA Public Key als JSON Web Key (JWK) nach https://datatracker.ietf.org/doc/html/rfc7517",
        "example": {
          "kty": "RSA",
          "n": "ofgWCuLjybRlzo0tZWJjNiuSfb4p4fAkd_wWJcyQoTbji9k0l8W26mPddx",
          "e": "AQAB"
        }
      },
      "commParticipant": {
        "required": [
          "id",
          "systemName",
          "operatorName",
          "operatorShortName",
          "supportedApps",
          "techSupport"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^([0-9]+\\.?)+$",
            "description": "KT-OID. Beim Anlegen eines KT-Kontos darf KT-OID auf Ebene 9 (CRM) beschränkt sein. In diesem Fall wird die OID um die fortlaufende KT-Nummer (Ebene 10) ergänzt."
          },
          "systemName": {
            "type": "string",
            "description": "Systemname"
          },
          "operatorName": {
            "type": "string",
            "description": "Betreibername"
          },
          "operatorShortName": {
            "type": "string",
            "description": "Betreibername-Kürzel"
          },
          "supportedApps": {
            "type": "array",
            "description": "Liste der unterstützten UCRI2-Applikation in spezifischen Versionen. Sobald ein KT eine Applikation unterstützt, müssen auch alle in der Applikation spezifizierten Nachrichten unterstützt werden.",
            "items": {
              "$ref": "#/components/schemas/appRef"
            }
          },
          "techSupport": {
            "$ref": "#/components/schemas/techSupport"
          },
          "key": {
            "$ref": "#/components/schemas/jwkRsaPub"
          },
          "status": {
            "type": "string",
            "enum": [
              "on",
              "off",
              "unknown"
            ],
            "description": "Verfügbarkeitsstatus des KT"
          }
        },
        "description": "Beschreibung eines Kommunikationsteilnehmers",
        "example": {
          "id": "1.2.3.1.276.5.1.58.28.2.1",
          "systemName": "ELS Essen",
          "operatorName": "Einsatzleitstelle Essen",
          "operatorShortName": "ELS E",
          "supportedApps": [
            {
              "appId": "incident",
              "appVersion": "0.1"
            },
            {
              "appId": "incident",
              "appVersion": "0.2"
            }
          ],
          "key": {
            "kty": "RSA",
            "n": "ofgWCuLjybRlzo0tZWJjNiuSfb4p4fAkd_wWJcyQoTbji9k0l8W26mPddx",
            "e": "AQAB"
          },
          "status": "off",
          "techSupport": {
            "phone": "001-555-1234",
            "e-mail": "abc@lst-essen.de"
          }
        }
      },
      "info": {
        "required": [
          "apiVersion",
          "crmProvider"
        ],
        "type": "object",
        "properties": {
          "apiVersion": {
            "type": "string",
            "description": "CRM API Version"
          },
          "crmProvider": {
            "type": "string",
            "description": "Hersteller des CRM Moduls"
          }
        },
        "description": "CRM Information",
        "example": {
          "apiVersion": "0.1",
          "crmProvider": "iSE"
        }
      }
    }
  }
}